version: "2"

networks:
  app-tier:
    driver: bridge


services:
  shrimp-frontend:
    image: shrimp-frontend:latest
    depends_on:
      - mongo
      - kafka
    networks:
      - app-tier
  shrimp-backend:
    image: shrimp-backend:latest
    depends_on:
      - mongo
      - kafka
    networks:
      - app-tier
  shrimp-gateway:
    image: shrimp-gateway:latest
    ports:
      - "8180:8180"
    depends_on:
      - shrimp-backend
      - shrimp-frontend
    networks:
      - app-tier
  #shrimp-trafficgenerator:
  #  image: shrimp-trafficgenerator
  #  ports:
  #    - "8090:8090"
  #  #volumes:
  #  #  - ./target/trafficgenerator-0.0.1-SNAPSHOT.jar:/usr/app/app.jar
  #  depends_on:
  #    - mongo
  #    - redis
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-tier
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 36000
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "CLIENT://:9092,EXTERNAL://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://kafka:9092,EXTERNAL://localhost:9093"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "CLIENT"
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - app-tier
  #redis:
  #  image: redis:latest
  #  expose:
  #    - "6379"
  #